name: puantaj
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  flutter_local_notifications: ^19.2.1
  table_calendar: ^3.0.9
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  responsive_framework: ^1.1.1
  supabase_flutter: ^2.9.0
  uuid: ^4.5.2
  path: ^1.9.0
  pdf: ^3.10.8
  path_provider: ^2.1.5
  open_file: ^3.5.11
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  file_selector: ^1.0.3
  share_plus: ^11.0.0
  device_info_plus: ^9.1.2
  google_sign_in: ^7.2.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.6.0
  bcrypt: ^1.2.0
  url_launcher: ^6.3.2
  credential_manager: ^2.0.8
  workmanager: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
    - assets/icons/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  adaptive_icon_background: "#212121" # Adaptif arka plan rengi (Örnek koyu gri)
  adaptive_icon_foreground: "assets/icons/icon.png" # Adaptif ön plan görseli

